[package]
name = "stream_multiplexer"
version = "0.9.2"
authors = ["Benjamin Halsted <bhalsted@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

categories = ["asynchronous", "network-programming"]
description = "Combines many streams into a few."
documentation = "https://docs.rs/stream_multiplexer"
keywords      = ["async", "asynchronous", "multiplex", "stream", "tokio"]
readme = "README.md"
repository    = "https://github.com/halzy/stream_multiplexer"

[dependencies]
byteorder = "1.3"
bytes = "0.5"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
thiserror = "1.0"
tokio = { version = "0.2.13", features = ["full"] }
tokio-util = { version = "0.2", features = ["codec"] }
tracing = { version = "0.1", features = ["log"] }
tracing-futures = "0.2"
tinyvec = { version = "0.3", features = ["alloc"] }

[dev-dependencies]
futures = { version = "0.3", default-features = false, features = ["alloc","std"] }
matches = "0.1"
tokio = { version = "0.2.13", features = ["full", "test-util"] }
tracing-subscriber = "0.2"
