[package]
name = "stream_multiplexer"
version = "0.15.0"
authors = ["Benjamin Halsted <bhalsted@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

categories = ["asynchronous", "network-programming"]
description = "Combines many streams into a few."
documentation = "https://docs.rs/stream_multiplexer"
keywords      = ["async", "asynchronous", "multiplex", "stream", "tokio"]
readme = "README.md"
repository    = "https://github.com/halzy/stream_multiplexer"

[dependencies]
byteorder = "1.3.4"
bytes = "0.5.6"
futures = { version = "0.3.5", default-features = false, features = ["alloc"] }
thiserror = "1.0.20"
tokio = { version = "0.2.21", features = ["full"] }
tokio-util = { version = "0.3.1", features = ["codec"] }
tracing = { version = "0.1.16", features = ["log"] }
tracing-futures = "0.2.4"
tinyvec = { version = "0.3.3", features = ["alloc"] }
either = "1.5.3"

[dev-dependencies]
futures = { version = "0.3.5", default-features = false, features = ["alloc","std"] }
matches = "0.1.8"
tokio = { version = "0.2.21", features = ["full", "test-util"] }
tokio-test = "0.2.1"
tracing-subscriber = "0.2.7"
